server:
  port: 80


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: cloud-order-service